# Spring Boot Application Configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

# Talon.One Integration
# Replace with actual API key and endpoint
app:
  talonone:
    apiKey: "YOUR_TALONONE_API_KEY"
    baseUrl: "https://YOUR_TALONONE_DOMAIN.talon.one/v1"
